# requirements.txt
snowflake-snowpark-python
streamlit
snowflake-connector-python


# name: app_environment
# channels:
#   - snowflake
# dependencies:
#   - python=3.11.*
#   - snowflake-snowpark-python=
#   - streamlit=
